### ISSUE TITLE
Is the function used wrong, and is inconsistent with the paper?

### ISSUE THREAD

**Issue by TachibanaYoshino** [ai-med/squeeze_and_excitation#3]
class ChannelSpatialSELayer(nn.Module):
    """
    Re-implementation of concurrent spatial and channel squeeze & excitation:
        *Roy et al., Concurrent Spatial and Channel Squeeze & Excitation in Fully Convolutional Networks, arXiv:1803.02579*
    """

    def __init__(self, num_channels, reduction_ratio=2):
        """
        :param num_channels: No of input channels
        :param reduction_ratio: By how much should the num_channels should be reduced
        """
        super(ChannelSpatialSELayer, self).__init__()
        self.cSE = ChannelSELayer(num_channels, reduction_ratio)
        self.sSE = SpatialSELayer(num_channels)

    def forward(self, input_tensor):
        """
        :param input_tensor: X, shape = (batch_size, num_channels, H, W)
        :return: output_tensor
        """
        output_tensor = torch.max(self.cSE(input_tensor), self.sSE(input_tensor))
        return output_tensor

In this class, is the function torch.max() of the penultimate line wrong, should it be torch.add?
![qq20190103135902](https://user-images.githubusercontent.com/36946777/50625019-1085ec00-0f60-11e9-8570-a2a8e3f2e15e.png)
In the paper, the d diagram of fig.1 shows the use of the add method. And the names of b and c in fig.1 are reversed.
Thanks

**Comment by abhi4ssj** [comment]
Hi,
In my initial Miccai paper, I used 'add'. Later I saw the results improved further using 'maxout', please refer to the paper published in IEEE TMI, link provided in ReadMe. 

Thanks
