### ISSUE TITLE
Evaluate Project & Excite on recent seg. challenges where test set label is hidden

### ISSUE THREAD

**Issue by JunMa11** [ai-med/squeeze_and_excitation#5]
Dear @abhi4ssj ,

Thanks for sharing the code.
Would it be possible for you to evaluate the network on recent segmentation challenges where test set label is hidden? such as [kits19](https://kits19.grand-challenge.org/), [structseg 19](https://structseg2019.grand-challenge.org/)

Best,
Jun

**Comment by abhi4ssj** [comment]
Hi Jun,

Thank you for the suggestion, we will definitely try them out :)

Best
Abhijit
