### ISSUE TITLE
dataset size

### ISSUE THREAD

**Issue by lxg15066629402** [ai-med/squeeze_and_excitation#6]
Excuse me, your network is directly sending data into the network structure. Can you tell me the scale of the MALC dataset and Visceral data? Thank your!!

**Comment by abhi4ssj** [comment]
I am not sure what you mean by scale. For MALC data each coronal slice of size 256*256 is sent whose resolution is 1 mm3. Similarly for Visceral data, I use axial slices of size 256*256 of voxel resolution 2mm3.
